### ISSUE TITLE
error while repo sync

### ISSUE THREAD

**Issue by li94575** [kernkonzept/manifest#1]
Fetching project virtio-net
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Not Found
fatal: repository 'https://github.com/virtio-net/' not found
remote: Not Found
fatal: repository 'https://github.com/virtio-net/' not found
error: Cannot fetch virtio-net from https://github.com/virtio-net

error: Exited sync due to fetch errors

**Comment by jermar** [comment]
Hi, from the output above, I assume you didn't use ham for checking out the L4Re sources. You should follow the [commands](https://github.com/kernkonzept/manifest/wiki/BUILDING#getting-the-fiasco-and-l4re-sources-using-ham) from our [tutorial](https://github.com/kernkonzept/manifest/wiki/BUILDING) for doing that. In case of any failure, please post also the steps to reproduce, including all command lines and arguments you used.

**Comment by icedieler** [comment]
Alternatively, if you want to manually check out the projects you have to use the correct remote URL which starts with `https://github.com/kernkonzept/` and is followed by the project name. In your case the project remote URL is `https://github.com/kernkonzept/virtio-net`

**Comment by jermar** [comment]
We might want to make it clear in the description of this repo that this is a ham manifest, not any other sort of manifest, such as repo manifest.

**Comment by jermar** [comment]
Closing this as invalid now as a wrong tool was used for checking out the manifest.
