### ISSUE TITLE
How to load root fs for VMs

### ISSUE THREAD

**Issue by Milon-yang** [kernkonzept/manifest#11]
Hi,

Another problem, the VMs loaded ramdisk as file system before. But in practical use，we need to load root file system in emmc or SDcard partition for VMs. 
Do you have any suggestion or any relevant documentation in this regard?

Thanks

**Comment by alacko** [comment]
Hi,
you mean that making eMMC available in one VM is not sufficient because you want to have storage for multiple VMs?

**Comment by Milon-yang** [comment]
I mean that I need to load root fs instead of ramdisk for VM，no matter for one or more VMs.
for example, in previous cases, we add "rd = "rom/ramdisk.gz"," in ned file for VM. 
Now if I want to use the real root file system, do I modify "rd" module in the ned file directly?

**Comment by alacko** [comment]
Yes, you can put some different filesystem image to rd. However, could you elaborate on what you mean with "real root file system"?

**Comment by Milon-yang** [comment]
OK, I mean the rootfs built-out from SDK. For example, "rootfs_ubuntu_focal_LS_arm64.tgz" is the real root file system for PCU platform, which is built out from NXP SDK. Usually, we use tools to flash it into SD card or EMMC partition, then boot the platform and go to ubuntu file system.

I have tried to replace  "ramdisk" to "rootfs_ubuntu_focal_LS_arm64.tgz" in ned file for VM, but it cant work.

**Comment by Milon-yang** [comment]
Hi，

In the default configuration，the VM will mount the root to ram0 (device 1:0), which is the file system in ramdisk.
<img width="418" alt="1640336155(1)" src="https://user-images.githubusercontent.com/85610217/147337206-fa5a31c9-c9e9-4805-8587-7507a7f0e977.png">

Now the mmc has been passed-through to VM, and I want to mount the root to mmcblk0p3  (device 179:3) instead of ram0. How should set it? 

Attachment is my ned file, thanks.
[uvmm-vm.zip](https://github.com/kernkonzept/manifest/files/7773882/uvmm-vm.zip)

**Comment by alacko** [comment]
Hi,
Please use `root=/dev/mmcblk0p3` instead of `rdinit=...`

**Comment by Milon-yang** [comment]
Hi,
 I changed the ned file as you described, but it still can not mount to mmcblk0p3.

<img width="384" alt="1640658011(1)" src="https://user-images.githubusercontent.com/85610217/147520631-416583f3-f277-456c-bd68-5f5a68c48986.png">

[uvmm-vm.zip](https://github.com/kernkonzept/manifest/files/7782414/uvmm-vm.zip)

**Comment by alacko** [comment]
Hi, please remove the rd line in the ned file. I believe the ramdisk is just use as an initrd, and could also change root to the mmcblk partition.

**Comment by Milon-yang** [comment]
Thanks a lot, it works OK in one VM.
By the way, does l4re support sharing EMMC hardware for multi-VMs? That is, can the root file system in the EMMC partition be accessed from multi-VMs at the same time?

**Comment by alacko** [comment]
L4Re can do this in general, however, there's no driver for the particular system at this time.

**Comment by jermar** [comment]
Closing as there is no action required.
