### ISSUE TITLE
Building on Ubuntu 22.04 for AMD64 Fails

### ISSUE THREAD

**Issue by georglauterbach** [kernkonzept/manifest#21]
I followed the [steps to build L4](https://github.com/kernkonzept/manifest/wiki/BUILDING#making-life-easier-with-makeconfboot-and-makeconflocal), but I am unable to get beyond this:

```console
user@host ~/git/l4re-ddf/build-l4  ➜ make config
make[1]: Entering directory '/home/notroot/git/l4re-ddf/l4'


*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

All build tools checked ok.
gcc -fPIC -Wall -pedantic -g -m32 -c /home/notroot/git/l4re-ddf/l4/tool/gendep/deptrack.c -o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/deptrack.32.o
gcc -fPIC -Wall -pedantic -g -m32 -c /home/notroot/git/l4re-ddf/l4/tool/gendep/syscall.c -o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/syscall.32.o
gcc -m32 -shared -Wl,--no-as-needed -Wl,-soname,/home/notroot/git/l4re-ddf/build-l4/tool/gendep/32/libgendep.so -ldl -o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/32/libgendep.so /home/notroot/git/l4re-ddf/build-l4/tool/gendep/deptrack.32.o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/syscall.32.o
gcc -fPIC -Wall -pedantic -g -m64 -c /home/notroot/git/l4re-ddf/l4/tool/gendep/deptrack.c -o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/deptrack.64.o
gcc -fPIC -Wall -pedantic -g -m64 -c /home/notroot/git/l4re-ddf/l4/tool/gendep/syscall.c -o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/syscall.64.o
gcc -m64 -shared -Wl,--no-as-needed -Wl,-soname,/home/notroot/git/l4re-ddf/build-l4/tool/gendep/64/libgendep.so -ldl -o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/64/libgendep.so /home/notroot/git/l4re-ddf/build-l4/tool/gendep/deptrack.64.o /home/notroot/git/l4re-ddf/build-l4/tool/gendep/syscall.64.o
ln -snf /home/notroot/git/l4re-ddf/l4 /home/notroot/git/l4re-ddf/build-l4/source
make[2]: '/home/notroot/git/l4re-ddf/build-l4/.config.all' is up to date.
make[1]: Leaving directory '/home/notroot/git/l4re-ddf/l4'
user@host ~/git/l4re-ddf/build-l4  ➜ make
make[1]: Entering directory '/home/notroot/git/l4re-ddf/l4'
make[3]: Nothing to be done for 'all'.
  [elf-patcher] ... Compiling /home/notroot/git/l4re-ddf/build-l4/tool/elf-patcher/elf-patcher
=== Building package "pkg/l4re-core/crtn" ===
  [crtn] ... Building Dependencies
=== Building package "pkg/l4re-core/ldscripts" ===
  [ldscripts] ... Building Dependencies
  [ldscripts] ... Building Dependencies
  [ldscripts] ... Compiling crti_s.o
  [ldscripts] ... Compiling kip_addr.o
  [ldscripts] ... Generating crti.o
  [ldscripts] ... Compiling crtn.o
  [ldscripts] ... Compiling crt1.o
  [ldscripts] ... Compiling crti.s.o
  [ldscripts] ... Compiling crtn.s.o
  [ldscripts] ... Compiling crt1.s.o
  [ldscripts] ... Generating ldscripts.pc
=== Building package "pkg/l4re-core/libgcc-pure" ===
  [libgcc-pure] ... Building Dependencies
  [libgcc-pure] ... Building Dependencies
  [libgcc-pure] ... Generating libgcc.a
  [libgcc-pure] ... Generating libgcc.so
  [libgcc-pure] ==> Installing libgcc.so to local build-tree
  [libgcc-pure] ... Generating libgcc-pure.pc
=== Building package "pkg/l4re-core/l4sys" ===
  [l4sys] ... Building Dependencies
  [l4sys] ... Building Dependencies
  [l4sys] ... Building Dependencies
  [l4sys] ... Compiling utcb.o
  [l4sys] ... Compiling errtostr.o
  [l4sys] ... Compiling kobject.o
  [l4sys] ==> Archiving into libl4sys.a
  [l4sys] ==> libl4sys.a built
  [l4sys] ... Compiling utcb.s.o
  [l4sys] ... Compiling errtostr.s.o
  [l4sys] ... Compiling kobject.s.o
  [l4sys] ==> Linking to shared libl4sys.so
make[5]: *** [/home/notroot/git/l4re-ddf/l4/mk/lib.mk:138: libl4sys.so] Illegal instruction (core dumped)
make[4]: *** [../../../../../mk/binary.inc:159: /home/notroot/git/l4re-ddf/build-l4/pkg/l4re-core/l4sys/lib/src/OBJ-amd64_gen-l4f] Error 2
make[3]: *** [../../../../mk/subdir.mk:44: src] Error 2
make[2]: *** [../../../mk/subdir.mk:44: lib] Error 2
make[1]: *** [mk/project.mk:129: pkg/l4re-core/l4sys] Error 2
make[1]: Leaving directory '/home/notroot/git/l4re-ddf/l4'
make: *** [Makefile:6: do-all-make-goals] Error 2
```

I am running Ubuntu 22.04 on an x86_64 machine:

```console
user@host ~  ➜ uname -a
Linux host 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
user@host ~  ➜ cat /etc/os-release -pp
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

All build dependencies are installed.

**Comment by georglauterbach** [comment]
I felt like Sherlock Holmes hunting down this issue. It was way weirder than anticipated, and not due to a missing dependency. Here is the solution:

When looking at `l4/mk/lib.mk:138`, I first hat to figure out what the real command looked like, so I enabled verbose logging with `V=1 make`. Therafter, I saw that `LD_PRELOAD` was used to load `libgendep.so`. This seemed weird to me, so I looked up what this `libgendep.so` does. Overwriting `open()` and Co. is not something you see every day. I found (after a lot of time) that removing the 64bit version removed the initial error about the illegal instruction (but of course, created a new one). Removing `LD_PRELOAD` entirely worked as well, but I was not sure what impacts this might have later, so this was not an option either.

I enabled verbose logging for the shared library as well and saw that I did what it was supposed to do, so I started it with different, unrelated programs, like GDB, which crashed as well. So I thought this was a more general problem with `libgendep.so`. I tried everything: from disabling SSE/AVX to starting programs in GDB with `LD_PRELOAD` and figuring out that is happening, but the behavior was very weird. After way too much time, I thought: hey, let's also use the core dump, so I tried to build L4Re, it crashed, I had enabled core dumps before, then spent 20 mins alone on finding the damn core dump file, then I started GDB with it (which is harder than anticipated because you have to start it with the right binary, which was `perl` here) and then I saw it: a crash at some address in a call to `open()` in `/lib/libachk.so` - wait, what?

Turns out: the VM I was working on is not 100% default Ubuntu/Linux, but has a few adjustments. [This SO post](https://stackoverflow.com/questions/42803422/why-invoke-open-in-libachk-so-instead-of-in-libc-so) seemed related, and indeed, there was an entry for `libachk.so` in `/etc/ld.so.preload`. `libachk.so` is intercepting calls to `open()` (and related functions) as well. When I removed it, the build succeeded. I never had any problems with this before, so I guess the interplay of `libgendep.so` and `libachk.so` was producing the issue.

So much time wasted for a single line in a single file... now I can build it, but running AMD64 posed another problem, but I will describe this in another issue.

**Comment by icedieler** [comment]
Hi @georglauterbach ,
glad you figured it out yourself. Reading through your story brings me to the conclusion that my attempt to reproduce this would have ended in a "works for me" situation ;-)
