### ISSUE TITLE
PCIe passthrough on ARMv8

### ISSUE THREAD

**Issue by vojojo** [kernkonzept/manifest#26]
Hi, 

I'm working on passing through a PCIe device (Wi-Fi module) to a Linux VM on an NXP i.MX8M Mini based platform with L4Re. The AMD64 NVMe example on this Wiki shows some parts of it but doesn't directly passthrough the PCIe device to the Linux guest.  Do you perhaps also have a PCIe device passthrough example available (ideally for an ARM64 target), or perhaps some more detailed information on how this can be approached, without passing through the complete PCIe root controller?

Thanks!

**Comment by alacko** [comment]
Hi,

fortunately there's a PCIe controller driver in io, which is required for this. Does the info in https://github.com/kernkonzept/io/blob/master/io/server/src/drivers/pcie_imx8.cc#L115 give you reasonable info to progress? If it works, starting io with -vv should give you also a dump of io's internal view of the PCIe bus and the Wifi module should be visible.

**Comment by vojojo** [comment]
Hi,

That is fortunate indeed! This also provides a good insight of how this works together with io.  Thanks!
