### ISSUE TITLE
Use yocto for building the Linux VM?

### ISSUE THREAD

**Issue by ivrabie** [kernkonzept/manifest#27]
Hi 

I am trying to run the l4re on RPI4. Is there a tutorial on how to build the Linux VM image using the yocto build system ?

**Comment by admlck** [comment]
Hi,

do you mean the Linux VM that would be running in a VM on the rpi4? There's really nothing special about that, just use any way that is convenient to you for build a custom Linux system. Or, for a start, just use a simple ramdisk, such as found in https://l4re.org/download/ramdisks/

**Comment by ivrabie** [comment]
What I meant was that I want to have this configuration :
![image](https://github.com/user-attachments/assets/e0a46679-2b0d-475e-8316-feed3e2736a2)
For me based on the current documentation is clear how get l4re running on RPI 4 the green part, what is not clear if should I include/configure something special in the yocto build so that the VMs would be compatible with L4RE  the red part. And if is there somewhere some tutorial at least for on VM?

**Comment by icedieler** [comment]
You do not need to include or configure special things in you yocto build. You need to make sure that the guest kernel has virtio and the respective device drivers (block, net, console) enabled.

**Comment by ivrabie** [comment]
Thank you @icedieler
