### ISSUE TITLE
platform: NXP/Freescale Layerscape

### ISSUE THREAD

**Issue by jiangfenghua123** [kernkonzept/manifest#3]
examples: Running a Linux guest VM and Running multiple Linux guest VMs
My obj is :Running  a Linux guest  not VM 
my select platform NXP/Freescale Layerscape
how to compile

**Comment by icedieler** [comment]
Hi,
I am understanding that you want to run a Linux guest with L4Re on the NXP Layerscape platform. Could you elaborate what your understanding of "Linux guest" is? Because I do not understand how this is different from running Linux in a VM.
What is your problem with compiling? Have you followed our [tutorial](https://github.com/kernkonzept/manifest/wiki/BUILDING) already?
Thanks and regards,
Matthias.

**Comment by jiangfenghua123** [comment]
l4Re hypevisor /service

qemu on the linux

I mean that  the L4re up the Hardware,linux geust on l4rE service


what is linux vm based on?





________________________________
发件人: Matthias Lange ***@***.***>
发送时间: 2021年6月3日 16:33
收件人: kernkonzept/manifest ***@***.***>
抄送: 蒋 凤华 ***@***.***>; Author ***@***.***>
主题: Re: [kernkonzept/manifest] platform: NXP/Freescale Layerscape (#3)


Hi,
I am understanding that you want to run a Linux guest with L4Re on the NXP Layerscape platform. Could you elaborate what your understanding of "Linux guest" is? Because I do not understand how this is different from running Linux in a VM.
What is your problem with compiling? Have you followed our tutorial<https://github.com/kernkonzept/manifest/wiki/BUILDING> already?
Thanks and regards,
Matthias.

―

**Comment by icedieler** [comment]
Hi,
it is still hard to get a clear picture. Maybe you can describe what your goal is, what you have tried to achieve it and what your current problem is.

> qemu on the linux

For that you have to choose the 'arm-virt' platform instead of Layerscape. Please work through our tutorial.

> I mean that the L4re up the Hardware,linux geust on l4rE service

That is covered by our tutorial. Please follow it through.

> what is linux vm based on?

What do you mean?

Cheers,
Matthias.

**Comment by jiangfenghua123** [comment]
Hi,
 Thanks for your reply.

L4re up the hardware,linux guest on l4re service.

I follow the Running a Linux guest VM,but i have a question.


print:
BOOTFS: [8118e000-8123c9c0] [C:107000] uvmm
  BOOTFS: [8123d000-81259e00] [C:109000] l4re
  BOOTFS: [8125a000-812d51b0] [C:10b000] ned
  BOOTFS: [812d6000-812d65ea] [C:10d000] virt-arm_virt-64.dtb
  BOOTFS: [812d8000-812d8dc0] [C:111000] vmm.lua
  BOOTFS: [812d9000-812d926b] [C:113000] uvmm.ned
  BOOTFS: [812da000-8386f200] [C:115000] Image.gz
  BOOTFS: [83870000-83bf0000] [C:117000] ramdisk-arm64.rd
MOE: cmdline: moe rom/uvmm.ned
MOE: Starting: rom/ned rom/uvmm.ned
MOE: loading 'rom/ned'
Ned says: Hi World!
Ned: loading file: 'rom/uvmm.ned'
VMM[vmbus]: 'vbus' capability not found. Hardware access not possible for VM.
VMM[main]: Hello out there.
VMM[]: ***@***.***,virtiocap: capability net is invalid.
VMM[vm]: Device creation for virtual device ***@***.*** failed. Disabling device.
VMM[ram]: Cleaning caches for device tree [111ff000-111ff6b2] ([93bff000])


I used virt-arm_virt-64.dts .
where vbus is set?

Best regards,
fenghua
________________________________
发件人: Matthias Lange ***@***.***>
发送时间: 2021年6月4日 15:26
收件人: kernkonzept/manifest ***@***.***>
抄送: 蒋 凤华 ***@***.***>; Author ***@***.***>
主题: Re: [kernkonzept/manifest] platform: NXP/Freescale Layerscape (#3)


Hi,
it is still hard to get a clear picture. Maybe you can describe what your goal is, what you have tried to achieve it and what your current problem is.

qemu on the linux

For that you have to choose the 'arm-virt' platform instead of Layerscape. Please work through our tutorial.

I mean that the L4re up the Hardware,linux geust on l4rE service

That is covered by our tutorial. Please follow it through.

what is linux vm based on?

What do you mean?

Cheers,
Matthias.

―

**Comment by icedieler** [comment]
Hi,

to understand the general concepts for Hardware pass-through I suggest you follow our [Tutorial on Hardware pass-through](https://github.com/kernkonzept/manifest/wiki/HwPassThrough).

Regards,
Matthias.

**Comment by jiangfenghua123** [comment]
Hi,
Thank you for your reply,
I have followed the instructions to solve the above problem .
There is a question?
The device is 4-core, and the VM is single-core after it is up. Can it be 2-core? 3-core? 

I have changed dts.

Best regards,

**Comment by jiangfenghua123** [comment]
Hi,
I have a question that how to generate ramdisk-armv8-64.cpio.gz ?

Best regards,

**Comment by icedieler** [comment]
Hi,

> I have a question that how to generate ramdisk-armv8-64.cpio.gz ?

You can find plenty of tutorials on how to create a ramdisk on the internet. However, the easiest is to extract an existing one, amend it and then to repackage it.

Good luck,
Matthias.

> 
> Best regards,

**Comment by icedieler** [comment]
Hi,

> Hi,
> Thank you for your reply,
> I have followed the instructions to solve the above problem .
> There is a question?
> The device is 4-core, and the VM is single-core after it is up. Can it be 2-core? 3-core?

Yes. You can have as many virtual CPUs per VM as there are physical ones. First you have to add more CPUs to the device tree (dts). Then you have to extend the scheduler CPU mask in the Lua script. Also make sure you have a SMP build of your guest kernel.

Cheers,
Matthias.
