### ISSUE TITLE
Wide character in syswrite at l4/tool/lib/L4/Image.pm line 302.

### ISSUE THREAD

**Issue by 512yottabytes** [kernkonzept/manifest#4]
Hello,
I have en error trying to compile l4re:
`Wide character in syswrite at /home/512yb/src/l4/tool/lib/L4/Image.pm line 302.`
How to solve it?

**Comment by icedieler** [comment]
Hi,

that is strange. Could you please attach the output from ```make report``` (run in your build directory) to this issue?

Thanks,
Matthias.

**Comment by Milon-yang** [comment]
Try as below：
1. Open the file "l4re-base-21.04.0/src/l4/tool/lib/L4/Image.pm"
2. Replace "." with "," in line 298 
    
![image](https://user-images.githubusercontent.com/85610217/125545211-4b5b6271-4175-4e4c-b7c2-1aa0a2fbb169.png)
3. Build it again

**Comment by alacko** [comment]
I believe this change destroys the purpose of this statement. I would highly appreciate if you could share the output of "locale" on your system as well as the output of "getent passwd | grep :$(id -u):" such that I am able to figure out what the issue really is. Unfortunately we over here in Europe sometime have our troubles with multi-byte strings as were able to use simpler ways of storing our language. Thanks a lot for your help.

**Comment by Milon-yang** [comment]
ubuntu18@ubuntu18-virtual-machine:~/milon/l4re-base-21.04.0$ getent passwd | grep :$(id -u):
ubuntu18:x:1000:1000:ubuntu18,,,:/home/ubuntu18:/bin/bash


But I don‘t understand what the output of "locale" mean

**Comment by alacko** [comment]
It tells me which locale you are using. I guess it is some asian language? I'm trying to figure out where the multi-byte issue is coming from.

**Comment by Milon-yang** [comment]
I am now using Chinese.

**Comment by alacko** [comment]
Ok, thanks.

**Comment by alacko** [comment]
Hi, believe I could fix this in l4re-base-21.07.0, please kindly check.

**Comment by icedieler** [comment]
The fix is also in the public release by now.
