### ISSUE TITLE
How to bring up multi-core by VM

### ISSUE THREAD

**Issue by Milon-yang** [kernkonzept/manifest#6]
I modify the file "virt-arm_virt-64.dts" , add cpu@1, cpu@2, cpu@3 device info in it (see attachmnet).
But it will print the below error information when boot
![image](https://user-images.githubusercontent.com/85610217/125569493-30772d35-aafd-4538-bb34-b0e3fdb66f6a.png)
Could you help to solve it.

[virt-arm_virt-64.zip](https://github.com/kernkonzept/manifest/files/6813826/virt-arm_virt-64.zip)

**Comment by alacko** [comment]
Multiple cores in a VM will only work if the host also has so many cores. And it probably hasn't. Start QEMU with -smp 4.

**Comment by Milon-yang** [comment]
We now use NXP ls1046a MPU to bring up. the CPU is Cortex-A72 with smp 4.

**Comment by alacko** [comment]
Did you implement CPU boot up in Fiasco's BSP such that all cores are started?

**Comment by Milon-yang** [comment]
We just bring up multiple cores using NXP SDK. and bring up single CPU by Fiasco's BSP.
We still have not implemented multi-cores boot up in Fiasco's BSP

**Comment by alacko** [comment]
Ok. When you have implemented the boot up the VMs shall also get the cores.

**Comment by Milon-yang** [comment]
Hi, 
I try to enable multi-core support in fiasco building
![image](https://user-images.githubusercontent.com/85610217/126032124-0e206cbf-b477-42d0-9de7-a28edd0f9f70.png)
then add 4 cpus node infomation in dts file.
but still can't bring-up multi-core in one VM.
DTS file and boot log are in attachment. Could you give some suggestion, thanks!
[dts_and_bootlog.zip](https://github.com/kernkonzept/manifest/files/6834524/dts_and_bootlog.zip)

**Comment by alacko** [comment]
I still believe that the Fiasco microkernel, i.e., the hypervisor, is only running on one core because the corresponding BSP code in Fiasco does not start the other cores of the system. Please check l4re-base-21.07.0 from l4re.org, it has the LS1046 BSP included now. Thanks.

**Comment by Milon-yang** [comment]
Problem solved, thanks a lot!
