### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by wucke13** [kernkonzept/manifest#7]
When following the instructions from the Wiki in a fresh debian 9 docker container, on the 

```bash
cd l4
make B=../build-i386
```
I received the following error:

```
E: Unable to locate package dtc
```

The package which was required is `device-tree-compiler`. This should be mentioned in the wiki.

**Comment by icedieler** [comment]
Hi,

thanks for reporting. We updated the wiki accordingly.

Best,
Matthias.
