### ISSUE TITLE
programming L4Re

### ISSUE THREAD

**Issue by irenge** [kernkonzept/manifest#8]
Is there a way to write a C++ program and run it in L4Re?

**Comment by icedieler** [comment]
Hi,
I am not sure in which direction your question is aiming. In fact the majority of L4Re programs is written in C++. See for example [io](https://github.com/kernkonzept/io) or [uvmm](https://github.com/kernkonzept/uvmm). The L4Re framework also features a full libstdc++.
Cheers,
Matthias.

**Comment by irenge** [comment]
Thanks for reply, I would like to know whether itv s possible to write a C
application and run it inside L4Re

Kind regards,
Jules

*..*

**Comment by jermar** [comment]
Hi Jules,

yes, this is possible. See for example the hello demonstration program here:
https://github.com/kernkonzept/hello/blob/master/server/src/main.c

As Matthias has written above, most of L4Re programs are written in C++. One can write a new C/C++ application and run it in an L4Re environment.

Cheers,
Jakub

**Comment by irenge** [comment]
Thanks

I am trying to try a simple fuzzer written in C++ on  L4Re just for
educational purposes as I am a student at UoM.

Am I supposed to write the Makefile and Control, prog.mk  and include
LICENSE.spdx ? Is there a guideline on porting application to L4?

Thanks,
Jules

*..*

**Comment by icedieler** [comment]
Which aspect of L4Re are you trying to fuzz? Which API are you aiming for? We have some experience in that regard and maybe we can give you some guidance. But we need to understand your use case and your goal.

**Comment by irenge** [comment]
I could try to fuzz the FIASCO or some of its environment tools, maybe you
could advise me on the simplest API to fuzz first, I am still a beginner in
fuzzing. I have a simple fuzzer that I tried successfully to run on and
fuzz Linux and on another microkernel called UniKernel.

Jules

*..*

**Comment by irenge** [comment]
My simple fuzzer fuzzes the system using a sequence of system calls API.

Kind regards,
Jules

*..*

**Comment by icedieler** [comment]
Hi,
so I understand that you are trying to fuzz the Fiasco kernel. You have to understand that the concepts and the system call API of Fiasco are fundamentally different compared to Linux or uni kernels. This makes it hard for a beginner to start with and I wouldn't advise you to do so. We worked with AFL in the past which mostly yielded useless results.
Best,
Matthias.

**Comment by irenge** [comment]
Thanks for the advice I am actually a student at University of Manchester.
It was just for learning purpose as part of my studies.
Are there any documents on system call API used and Is there any guideline
on how run a C++ code on L4Re ?

Kind regards,
Jules

*..*

**Comment by icedieler** [comment]
Maybe you should start to learn about the general principles of microkernel systems e.g. with this course on [microkernel construction](https://tu-dresden.de/ing/informatik/sya/professur-fuer-betriebssysteme/studium/vorlesungen/mikrokernkonstruktion).
Again there is nothing special about programs written in C++. You have to build them using the L4Re build system. You can follow the components provided in our github and adapt the How Tos accordingly.

**Comment by irenge** [comment]
Hi Mathias

Thanks for the link. I am enjoying it right now.

Is there a way of accessing the videos ?

I can provide my student email  if necessary.

Thank you
Jules

*..*

**Comment by icedieler** [comment]
Hi,
unfortunately the videos are not publicly available. You may ask the producers why this is so and whether they plan to change that in the future.
